-- =========================================================
-- V1__init_schema.sql  (H2 2.x)
-- =========================================================
-- Note:
-- - ENUM 미지원 → VARCHAR + CHECK 제약
-- - DATETIME/INSTANT → TIMESTAMP
-- - UUID 타입 사용
-- - 필요한 기본 FK/인덱스만 포함 (최소 + 실용)
-- =========================================================

-- ---------- Drop (자식 → 부모) ----------
DROP TABLE IF EXISTS point_history;
DROP TABLE IF EXISTS point_cancel;
DROP TABLE IF EXISTS point_use_detail;
DROP TABLE IF EXISTS point_use;
DROP TABLE IF EXISTS point_grant;
DROP TABLE IF EXISTS members;

-- =========================================================
-- 1) MEMBERS (수정본)
-- =========================================================
CREATE TABLE members (
                         member_seq         BIGINT       NOT NULL GENERATED BY DEFAULT AS IDENTITY, -- PK
                         member_id          VARCHAR(36),                -- 외부 시스템 식별자(옵션)
                         name               VARCHAR(100),
                         role               VARCHAR(30)  NOT NULL DEFAULT 'CUSTOMER',  -- ✅ 기본 CUSTOMER
                         created_date       TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
                         modified_date      TIMESTAMP,
                         created_by         BIGINT,
                         modified_by        BIGINT,
                         CONSTRAINT pk_members PRIMARY KEY (member_seq),
                         CONSTRAINT ck_members_role CHECK (role IN ('CUSTOMER','MANAGER'))  -- ✅ 역할 검증
);
CREATE SEQUENCE IF NOT EXISTS members_seq START WITH 1 INCREMENT BY 50;
-- =========================================================
-- 2) POINT_GRANT (적립 원장: Lot)
-- =========================================================
CREATE TABLE point_grant (
                             grant_id           UUID         NOT NULL,
                             member_seq         BIGINT       NOT NULL,
                             amount             BIGINT       NOT NULL,    -- > 0
                             remaining_amount   BIGINT       NOT NULL,    -- >= 0 AND <= amount
                             grant_type         VARCHAR(16)  NOT NULL,    -- MANUAL | AUTO | REGRANT
                             expires_at         TIMESTAMP    NOT NULL,
                             status             VARCHAR(16)  NOT NULL DEFAULT 'ACTIVE', -- ACTIVE | CANCELLED | EXPIRED
                             note               VARCHAR(255),
                             created_date       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
                             modified_date      TIMESTAMP,
                             created_by         BIGINT,
                             modified_by        BIGINT,
                             CONSTRAINT pk_point_grant PRIMARY KEY (grant_id),
                             CONSTRAINT fk_point_grant_member
                                 FOREIGN KEY (member_seq) REFERENCES members(member_seq),
                             CONSTRAINT ck_point_grant_amount_pos
                                 CHECK (amount > 0),
                             CONSTRAINT ck_point_grant_remaining_nonneg
                                 CHECK (remaining_amount >= 0),
                             CONSTRAINT ck_point_grant_remaining_le_amount
                                 CHECK (remaining_amount <= amount),
                             CONSTRAINT ck_point_grant_type
                                 CHECK (grant_type IN ('MANUAL','AUTO','REGRANT')),
                             CONSTRAINT ck_point_grant_status
                                 CHECK (status IN ('ACTIVE','CANCELLED','EXPIRED'))
);

CREATE INDEX idx_point_grant_member_expires
    ON point_grant (member_seq, expires_at);

-- =========================================================
-- 3) POINT_USE (사용 헤더)
-- =========================================================
CREATE TABLE point_use (
                           use_id            UUID         NOT NULL,
                           member_seq        BIGINT       NOT NULL,
                           order_no          VARCHAR(64)  NOT NULL,
                           used_amount       BIGINT       NOT NULL,      -- > 0
                           status            VARCHAR(24)  NOT NULL DEFAULT 'USED', -- USED | PARTIAL_CANCELLED | CANCELLED
                           created_date      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
                           modified_date     TIMESTAMP,
                           created_by        BIGINT,
                           modified_by       BIGINT,
                           CONSTRAINT pk_point_use PRIMARY KEY (use_id),
                           CONSTRAINT fk_point_use_member
                               FOREIGN KEY (member_seq) REFERENCES members(member_seq),
                           CONSTRAINT ck_point_use_amount_pos
                               CHECK (used_amount > 0),
                           CONSTRAINT ck_point_use_status
                               CHECK (status IN ('USED','PARTIAL_CANCELLED','CANCELLED'))
);

CREATE INDEX idx_point_use_member ON point_use (member_seq);
CREATE INDEX idx_point_use_order  ON point_use (order_no);

-- =========================================================
-- 4) POINT_USE_DETAIL (사용 상세 매핑)
-- =========================================================
CREATE TABLE point_use_detail (
                                  use_detail_id     UUID       NOT NULL,
                                  use_id            UUID       NOT NULL,
                                  grant_id          UUID       NOT NULL,
                                  amount            BIGINT     NOT NULL,     -- > 0
                                  created_date      TIMESTAMP  DEFAULT CURRENT_TIMESTAMP,
                                  modified_date     TIMESTAMP,
                                  created_by        BIGINT,
                                  modified_by       BIGINT,
                                  CONSTRAINT pk_point_use_detail PRIMARY KEY (use_detail_id),
                                  CONSTRAINT fk_pud_use
                                      FOREIGN KEY (use_id) REFERENCES point_use(use_id),
                                  CONSTRAINT ck_pud_amount_pos
                                      CHECK (amount > 0)
);
CREATE TABLE point_cancel (
                              cancel_id              UUID       NOT NULL,
                              use_id                 UUID       NOT NULL,
                              use_detail_id          UUID       NOT NULL,
                              cancel_amount          BIGINT     NOT NULL,     -- > 0
                              regrant_needed_amount  BIGINT     NOT NULL DEFAULT 0, -- >= 0
                              created_date           TIMESTAMP  NOT NULL DEFAULT CURRENT_TIMESTAMP,
                              modified_date          TIMESTAMP,
                              created_by             BIGINT,
                              modified_by            BIGINT,
                              CONSTRAINT pk_point_cancel PRIMARY KEY (cancel_id),
                              CONSTRAINT fk_point_cancel_use_detail
                                  FOREIGN KEY (use_detail_id) REFERENCES point_use_detail(use_detail_id),
                              CONSTRAINT fk_point_cancel_use
                                  FOREIGN KEY (use_id) REFERENCES point_use(use_id),
                              CONSTRAINT ck_point_cancel_amount_pos
                                  CHECK (cancel_amount > 0),
                              CONSTRAINT ck_point_cancel_regrant_nonneg
                                  CHECK (regrant_needed_amount >= 0)
);

-- =========================================================
-- 5) POINT_CANCEL (사용 취소 헤더)
-- =========================================================
CREATE INDEX idx_pud_grant  ON point_use_detail (grant_id);
CREATE INDEX idx_point_cancel_use ON point_cancel (use_id);
CREATE INDEX idx_point_cancel_use_detail ON point_cancel (use_detail_id);

-- =========================================================
-- 6) POINT_HISTORY (감사 로그 - append-only)
-- =========================================================
CREATE TABLE point_history (
                               history_id       UUID         NOT NULL,
                               member_seq       BIGINT       NOT NULL,
                               event_type       VARCHAR(16)  NOT NULL,   -- GRANT | GRANT_CANCEL | USE | USE_CANCEL | EXPIRE | REGRANT
                               ref_type         VARCHAR(32),             -- GRANT / USE / CANCEL / REGRANT ...
                               ref_id           UUID,
                               delta            BIGINT       NOT NULL,   -- +/-
                               balance_after    BIGINT       NOT NULL,
                               created_date     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
                               modified_date    TIMESTAMP,
                               created_by       BIGINT,
                               modified_by      BIGINT,
                               CONSTRAINT pk_point_history PRIMARY KEY (history_id),
                               CONSTRAINT fk_point_history_member
                                   FOREIGN KEY (member_seq) REFERENCES members(member_seq),
                               CONSTRAINT ck_point_history_event_type
                                   CHECK (event_type IN ('GRANT','GRANT_CANCEL','USE','USE_CANCEL','EXPIRE','REGRANT'))
);

-- =========================================================
-- 6) point_policy (포인트 정책 )
-- =========================================================

CREATE TABLE point_policy (
    policy_id     UUID        DEFAULT RANDOM_UUID() PRIMARY KEY,
    scope         VARCHAR(16) NOT NULL,            -- GLOBAL | MEMBER
    policy_type   VARCHAR(32) NOT NULL,            -- MAX_GRANT_PER_TX | MAX_BALANCE_PER_MEMBER
    member_seq    BIGINT,                          -- MEMBER일 때 대상 회원
    active        BOOLEAN     NOT NULL DEFAULT TRUE,
    policy_value  BIGINT      NOT NULL,
    created_date  TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_date TIMESTAMP,
    created_by    BIGINT,
    modified_by   BIGINT,
    CONSTRAINT ck_scope_member
        CHECK (
            (scope = 'GLOBAL' AND member_seq IS NULL) OR
            (scope = 'MEMBER' AND member_seq IS NOT NULL)
            ),
    CONSTRAINT ck_scope_enum
        CHECK (scope IN ('GLOBAL','MEMBER')),
    CONSTRAINT ck_policy_type_enum
        CHECK (policy_type IN ('MAX_GRANT_PER_TX','MAX_BALANCE_PER_MEMBER')),
    CONSTRAINT ck_policy_value_by_type
        CHECK (
            (policy_type = 'MAX_GRANT_PER_TX' AND policy_value >= 1) OR
            (policy_type = 'MAX_BALANCE_PER_MEMBER' AND policy_value >= 0)
            )
);
-- (대체: 성능용 일반 인덱스 / 유니크 제약은 앱 레벨에서 보완)
CREATE INDEX ix_point_policy_global  ON point_policy (policy_type, scope, active);
CREATE INDEX ix_point_policy_member  ON point_policy (member_seq, policy_type, active);
CREATE INDEX ix_point_policy_member_active ON point_policy (member_seq, active);
